### ISSUE TITLE
2d walking problem setup

### ISSUE THREAD

**Issue by hammoudbilal** [nmansard/crocoddyl#1]
Hi, i am trying to explore simpler walking models in 2d, so instead of a full 3d free flyer i use a 2d base (built-in pinocchio Planar joint). Using this, the full 6d jacobians will be rank deficient off-course. 

I was looking into setting up the contact model as 3d two linear dof's and one angular dof, but looking at the build in 3d model in crocoddyl, it seems that the 3d model supports 3 linear dof's instead. Please correct me if my understanding of this is wrong ? 

also if I understand it correctly can you advise on how to set it up properly ?

**Comment by nmansard** [comment]
Hi @hammoudbilal . Nice to see you here.
Sorry, this repo is only a mirror and I apparently did not properly listen to the inputs. Very sorry for that.
The actual repo is in out gitlab server: 
https://gepgitlab.laas.fr/loco-3d/crocoddyl/
It is public (read access to issues and git tree) but you need to create an account to be allowed to post on it. As a member of the Memmo project, you should be allowed to create an account. Contact memmo-admin@laas.fr if you do not easily create such an account. 
See you in gepgitlab!
